In [2]:
import numpy
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [3]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list) if not isinstance(python_list, np.ndarray) else python_list
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [4]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [5]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [6]:
ones = np.full(12, 1)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [7]:
ones = ones.reshape(3, 4)
print(ones.shape)

(3, 4)


6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [8]:
Z = np.arange(1, 21).reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [9]:
first = np.random.randint(-10, 11, 15)
print(first)
second = np.flip(first)
print(second)

[  7   6 -10   4   4  -4   2   1  -3   0   0  -3  -5  -3   2]
[  2  -3  -5  -3   0   0  -3   1   2  -4   4   4 -10   6   7]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [10]:
first = np.random.randint(-15, 16, (5, 5))
print(first)
first[first < 0] = first[first < 0] ** 2
print(first)

[[-14  10  -6   9  10]
 [ 10  -9   4  -3   8]
 [-13   8   4 -12   7]
 [  6   7 -15  -6 -12]
 [  7  11   9   2  -3]]
[[196  10  36   9  10]
 [ 10  81   4   9   8]
 [169   8   4 144   7]
 [  6   7 225  36 144]
 [  7  11   9   2   9]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [11]:
first = np.random.randint(-15, 16, (3, 5))
print(np.max(first), np.min(first))
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))

14 -15
[-1.66666667  6.33333333 -0.66666667 -6.         -7.66666667]
[-9.   1.4  1.8]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [12]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print("Error matrix dot")

[[  15  -80  107]
 [ -42 -127  -56]]


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [13]:
matrix = np.random.uniform(2, 12, (5, 5))
matrix = np.tril(matrix, 0)
print(matrix)

[[ 6.58835396  0.          0.          0.          0.        ]
 [10.28450267  4.29353724  0.          0.          0.        ]
 [ 9.62801522 10.93960739  5.70162106  0.          0.        ]
 [10.78562615  9.09245076 10.38314796  7.01911029  0.        ]
 [ 5.07208254 11.1691097   9.66760682  4.59489819  7.75685223]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [14]:
matrix = np.random.normal(10, 2, (5, 5))
np.fill_diagonal(matrix, 0)

print(matrix)

[[ 0.         11.05033088 10.87955378  9.77453565 12.12581654]
 [ 8.31218263  0.         12.1111942  11.55229277 10.23897767]
 [11.62498205 11.66799705  0.          9.89014058 10.89963831]
 [ 9.62736428 14.40633634  8.47054328  0.         10.67115755]
 [11.34381505 13.14599705 12.09590132 10.60206471  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [22]:
a = np.random.randint(0, 2, 5)
print(a)
b = np.random.randint(0, 2, 5)
print(b)
equal = np.array_equal(a, b)
print(equal)

[1 1 1 1 0]
[1 0 0 0 0]
False


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [31]:
r, c = np.random.randint(3, 8), np.random.randint(2, 13)
a = np.random.rand(r, c)
print(a)
N = np.random.randint(1, a.size // 2 + 1)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[0.32107699 0.98734361 0.67452306 0.79724233 0.83133844 0.50631717
  0.7478822 ]
 [0.75383048 0.70353859 0.77217988 0.69684631 0.1547144  0.78763322
  0.4222616 ]
 [0.94079578 0.47353341 0.74283244 0.23974569 0.66430481 0.82736345
  0.8631295 ]
 [0.84990246 0.30062649 0.74882543 0.04943033 0.12623932 0.76379232
  0.20555725]
 [0.83881732 0.62075134 0.88382117 0.25933701 0.96414221 0.45516779
  0.45854117]
 [0.16847369 0.87496477 0.70666907 0.16440079 0.77567645 0.64938603
  0.74623465]
 [0.47792047 0.39302493 0.30303154 0.55459015 0.69379019 0.94363943
  0.92131302]]
22
[0.77217988 0.45516779 0.94363943 0.45516779 0.83881732 0.70353859
 0.87496477 0.77567645 0.45516779 0.78763322 0.64938603 0.67452306
 0.83133844 0.25933701 0.50631717 0.67452306 0.83881732 0.1547144
 0.50631717 0.88382117 0.1547144  0.98734361]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [39]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)

nan_mask = np.isnan(a)
if np.any(nan_mask):
    a[np.isnan(a)] = 0

inf_mask = np.isinf(a)
if np.any(inf_mask):
    a[np.isinf(a)] = 0
print(a)

[ 1. nan inf]
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [60]:
axis = np.random.randint(1, 5)
shape = np.random.randint(0, 1, size=axis)
random_array = np.random.random(size=shape)
print(matrix.ndim)

4


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [62]:
matrix = np.random.normal(50, 10, (10, 3))
print(matrix)
indexes = matrix.argmax(axis=1)
print(indexes)
max_elements = matrix[np.arange(matrix.shape[0]), indexes]
print(max_elements)

[[52.30263205 57.43518313 51.70655415]
 [39.2624626  60.19316968 55.24248551]
 [64.22228898 32.73075794 53.6170146 ]
 [69.72798374 47.17372814 44.86073739]
 [42.86127818 61.16152711 50.46477446]
 [47.4691909  38.1281127  44.76796678]
 [46.62906183 44.58202813 51.42572359]
 [41.58573676 57.50337684 70.11400148]
 [43.99702194 41.04941884 39.48610137]
 [65.08492823 35.78947804 60.73980306]]
[1 1 0 0 1 0 2 2 0 0]
[57.43518313 60.19316968 64.22228898 69.72798374 61.16152711 47.4691909
 51.42572359 70.11400148 43.99702194 65.08492823]


18. Задача теорвер. Реализовать решение методом Монте Карло. 1 и 2 подзадачи полностью из 3-ей выбрать любой пункт
Кто сможет обойтись без циклов для создания серии экспериментов - отдельный плюсик!!!

1. Бросаем два игральных кубика: красный и синий. Определите вероятность того, что цифры на красном и синем кубиках совпадут.
2. В этом же эксперименте с кубиками нужно найти наиболее вероятную сумму цифр на кубиках.
3. Наудачу выбирается одно число от 1 до 20. Считая все числа равновозможными, определите вероятность того, что выбранное число:
* чётно;
* делится на 3;
* делится и на 2, и на 3;
* не делится ни на 2, ни на 3;
* имеет сумму цифр 9;
* имеет сумму цифр, делящуюся на 3.

In [93]:
# Задача 1:
red_die = np.random.randint(1, 7, size=1000000)
blue_die = np.random.randint(1, 7, size=1000000)
matching_numbers = np.sum(red_die == blue_die)
probability_matching = matching_numbers / 1000000
print("Задача 1: Вероятность что цифры на красном и синем кубиках совпали:", probability_matching)

# Задача 2:
sum_of_numbers = red_die + blue_die
most_common_sum = np.argmax(np.bincount(sum_of_numbers))
print("Задача 2: Наиболее вероятная сумма цифр на кубиках:", most_common_sum)

# Задача 3:
random_number = np.random.randint(1, 21, size=1000000)
even_probability = np.mean(random_number % 2 == 0)
divisible_by_3_probability = np.mean(random_number % 3 == 0)
divisible_by_2_and_3_probability = np.mean((random_number % 2 == 0) & (random_number % 3 == 0))
not_divisible_by_2_or_3_probability = np.mean((random_number % 2 != 0) & (random_number % 3 != 0))
sum_of_digits_9_probability = np.mean((random_number==9) | (random_number==18))
sum_of_digits_divisible_by_3_probability = np.mean(random_number%3==0)

print("Задача 3: Вероятность, что выбранное число:")
print("\tчётно:", even_probability)
print("\tделится на 3:", divisible_by_3_probability)
print("\tделится и на 2, и на 3:", divisible_by_2_and_3_probability)
print("\tне делится ни на 2, ни на 3:", not_divisible_by_2_or_3_probability)
print("\tимеет сумму цифр 9:", sum_of_digits_9_probability)
print("\tимеет сумму цифр, делящуюся на 3:", sum_of_digits_divisible_by_3_probability)


Задача 1: Вероятность что цифры на красном и синем кубиках совпали: 0.165836
Задача 2: Наиболее вероятная сумма цифр на кубиках: 7
Задача 3: Вероятность, что выбранное число:
	чётно: 0.500471
	делится на 3: 0.300078
	делится и на 2, и на 3: 0.150397
	не делится ни на 2, ни на 3: 0.349848
	имеет сумму цифр 9: 0.100169
	имеет сумму цифр, делящуюся на 3: 0.300078
