In [94]:
import numpy
import numpy as np

1. Задание
- проверьте тип объекта python_list
- если это не numpy ndarray, то преобразуйте к нему
- проверьте, что на выходе вы получили объект python_list желаемого типа

In [95]:
python_list = [1, 12, 13, 45, 76, 45, 98, 0]
print(type(python_list))
python_list = np.array(python_list) if not isinstance(python_list, np.ndarray) else python_list
print(type(python_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Задание
- создайте одномерный массив numpy из 10 элементов заполненный числом 1.5

In [96]:
z = np.full(10, 1.5)
print(z)

[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]


3. Задание
- создайте двумерный массив numpy из 25 элементов заполненный числом 0

In [97]:
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Задание
- создайте одномерный массив numpy из 12 элементов заполненный числом 1

In [98]:
ones = np.full(12, 1)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1]


5. Задание
- преобразуйте массив из предыдущего задания к матрице 3 на 4
- выведите размерность полученного массива

In [99]:
ones = ones.reshape(3, 4)
print(ones.shape)

(3, 4)


6. Задание
- создайте матрицу 4 на 5 заполненную числами от 1 до 20
- замените элемент в 3-й строке 4-м столбце на -99

In [100]:
Z = np.arange(1, 21).reshape(4, 5)
print(Z)
Z[2, 3] = -99
print(Z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 -99  15]
 [ 16  17  18  19  20]]


7. Задание
- создайте вектор длинной 15 со случайными целыми числами в диапазоне от -10 до 10
- сделайте реверс вектора

In [101]:
first = np.random.randint(-10, 11, 15)
print(first)
second = np.flip(first)
print(second)

[ -9  -1 -10   2   2   8   2 -10   5  -6  -9  -7  -4  -1  -5]
[ -5  -1  -4  -7  -9  -6   5 -10   2   8   2   2 -10  -1  -9]


8. Задание
- создайте матрицу 5 на 5 со случайными целыми числами в диапазоне от -15 до 15
- замените отрицательные элементы на их квадраты

In [102]:
first = np.random.randint(-15, 16, (5, 5))
print(first)
first[first < 0] = first[first < 0] ** 2
print(first)

[[ -8  -7   0 -12   5]
 [-10  15  -7   1   4]
 [ -4  13  14   7  15]
 [-12   1  -1   9 -15]
 [ 15   5  13   3   0]]
[[ 64  49   0 144   5]
 [100  15  49   1   4]
 [ 16  13  14   7  15]
 [144   1   1   9 225]
 [ 15   5  13   3   0]]


9. Задание
- создайте матрицу 3 на 5 со случайными целыми числами в диапазоне от -15 до 15
- найдите максимум и минимум
- найдите среднее по столбцам
- найдите среднее по строкам

In [103]:
first = np.random.randint(-15, 16, (3, 5))
print(np.max(first), np.min(first))
print(np.mean(first, axis=0))
print(np.mean(first, axis=1))

14 -12
[ 1.33333333 -4.33333333  4.         -1.66666667  2.33333333]
[ 2.6 -5.2  3.6]


10. Задание
- даны две матрицы
- убедитесь, что их можно пермножить
- произведите операцию умножения матриц, если это возможно, иначе выведите ошибку

In [104]:
a = np.random.randint(-10, 10, (2, 5))
first_axis = np.random.randint(4, 6)
b = np.random.randint(-10, 10, (first_axis, 3))
if a.shape[1] == b.shape[0]:
    print(a @ b)
else:
    print("Error matrix dot")

Error matrix dot


11. Задание
- создайте матрицу 5 на 5 заполненную равномерным распределением с диапазоно 2-12
- заполните все элементы ниже главной диагонали нулями

In [105]:
matrix = np.random.uniform(2, 12, (5, 5))
matrix = np.tril(matrix, 0)
print(matrix)

[[ 6.33536841  0.          0.          0.          0.        ]
 [10.91237509  7.05463827  0.          0.          0.        ]
 [10.92518852  3.32429616  7.47531775  0.          0.        ]
 [ 8.12386953  9.16613121  4.76135338  5.14250732  0.        ]
 [10.10761938  9.15084664  8.87104888  7.79895532  6.33690267]]


12. Задание
- создайте матрицу 5 на 5 заполненную нормальным распределением с парметрами среднее 10 и отклонение 2
- заполните все элементы на главной диагонали нулями

In [106]:
matrix = np.random.normal(10, 2, (5, 5))
np.fill_diagonal(matrix, 0)

print(matrix)

[[ 0.         13.62888771  7.43044479 10.77250187  9.37632374]
 [10.75960447  0.          9.11355443  9.83888884 10.55819235]
 [11.7842425  12.9921329   0.          7.60320641  8.19608352]
 [11.09266497  9.71280088  9.15361412  0.          9.23618017]
 [10.85728463  9.39183762  6.20373101 11.57349063  0.        ]]


13. Задание
- дано два массива, проверить одинаковы ли они

In [107]:
a = np.random.randint(0, 2, 5)
print(a)
b = np.random.randint(0, 2, 5)
print(b)
equal = np.array_equal(a, b)
print(equal)

[1 1 1 1 1]
[0 1 0 0 0]
False


14. Задание
- сгенерируйте матрицу случайного размера:
 - строк от 3 до 7
 - столбцов от 2 до 12
- сгенерируйте число N - размер выборки так, чтобы оно не превышало половину количества элементов сгенерированной матрицы, но было больше 0
- сделайте случайную выборку N элементов

In [108]:
r, c = np.random.randint(3, 8), np.random.randint(2, 13)
a = np.random.rand(r, c)
print(a)
N = np.random.randint(1, a.size // 2 + 1)
print(N)
sample = np.random.choice(a.flatten(), N)
print(sample)

[[0.85319818 0.13483771 0.60327928 0.03828407]
 [0.01745773 0.73216532 0.4712058  0.51797685]
 [0.90204034 0.5006751  0.79039021 0.73384846]
 [0.51228295 0.314048   0.27355453 0.11526843]
 [0.94375055 0.34224107 0.46978055 0.9378755 ]
 [0.91683284 0.12028739 0.3809484  0.06843435]]
9
[0.91683284 0.73384846 0.5006751  0.94375055 0.3809484  0.85319818
 0.27355453 0.91683284 0.34224107]


15. Задание
- дан вектор, проверить есть в нем Nan
- проверить есть в нем знак бесконечности
- заполнить их нулями

In [109]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)

nan_mask = np.isnan(a)
if np.any(nan_mask):
    a[np.isnan(a)] = 0

inf_mask = np.isinf(a)
if np.any(inf_mask):
    a[np.isinf(a)] = 0
print(a)

[ 1. nan inf]
[1. 0. 0.]


16. Задание
- сгенерировать массив с произвольным числом осей
- определить сколько у него осей

In [110]:
axis = np.random.randint(1, 5)
shape = np.random.randint(0, 1, size=axis)
random_array = np.random.random(size=shape)
print(matrix.ndim)

2


17. Задание
- сгенерируйте матрицу 10 на 3 с нормальным распределением, среднее 50, отклонение 10
- найдите индексы максимальных элементов в каждой строке
- найдите сами элементы

In [111]:
matrix = np.random.normal(50, 10, (10, 3))
print(matrix)
indexes = matrix.argmax(axis=1)
print(indexes)
max_elements = matrix[np.arange(matrix.shape[0]), indexes]
print(max_elements)

[[47.21050205 43.12597015 45.88056518]
 [63.60109026 35.24825827 56.8929539 ]
 [53.10538933 58.29012516 52.69972391]
 [52.68973676 42.33243609 39.4569364 ]
 [50.67557362 66.40104527 43.4410356 ]
 [70.56867517 44.54348608 26.70956125]
 [49.72157567 56.05184417 65.73623513]
 [55.83240547 57.19651251 48.33985185]
 [52.13634675 40.14197101 54.39880372]
 [21.43633265 56.61198295 51.5619915 ]]
[0 0 1 0 1 0 2 1 2 1]
[47.21050205 63.60109026 58.29012516 52.68973676 66.40104527 70.56867517
 65.73623513 57.19651251 54.39880372 56.61198295]


18. Задача теорвер. Реализовать решение методом Монте Карло. 1 и 2 подзадачи полностью из 3-ей выбрать любой пункт
Кто сможет обойтись без циклов для создания серии экспериментов - отдельный плюсик!!!

1. Бросаем два игральных кубика: красный и синий. Определите вероятность того, что цифры на красном и синем кубиках совпадут.
2. В этом же эксперименте с кубиками нужно найти наиболее вероятную сумму цифр на кубиках.
3. Наудачу выбирается одно число от 1 до 20. Считая все числа равновозможными, определите вероятность того, что выбранное число:
* чётно;
* делится на 3;
* делится и на 2, и на 3;
* не делится ни на 2, ни на 3;
* имеет сумму цифр 9;
* имеет сумму цифр, делящуюся на 3.

In [112]:
# Задача 1:
red_die = np.random.randint(1, 7, size=1000000)
blue_die = np.random.randint(1, 7, size=1000000)
matching_numbers = np.sum(red_die == blue_die)
probability_matching = matching_numbers / 1000000
print("Задача 1: Вероятность что цифры на красном и синем кубиках совпали:", probability_matching)

# Задача 2:
sum_of_numbers = red_die + blue_die
most_common_sum = np.argmax(np.bincount(sum_of_numbers))
print("Задача 2: Наиболее вероятная сумма цифр на кубиках:", most_common_sum)

# Задача 3:
random_number = np.random.randint(1, 21, size=1000000)
even_probability = np.mean(random_number % 2 == 0)
divisible_by_3_probability = np.mean(random_number % 3 == 0)
divisible_by_2_and_3_probability = np.mean((random_number % 2 == 0) & (random_number % 3 == 0))
not_divisible_by_2_or_3_probability = np.mean((random_number % 2 != 0) & (random_number % 3 != 0))
sum_of_digits_9_probability = np.mean((random_number==9) | (random_number==18))
sum_of_digits_divisible_by_3_probability = np.mean(random_number%3==0)

print("Задача 3: Вероятность, что выбранное число:")
print("\tчётно:", even_probability)
print("\tделится на 3:", divisible_by_3_probability)
print("\tделится и на 2, и на 3:", divisible_by_2_and_3_probability)
print("\tне делится ни на 2, ни на 3:", not_divisible_by_2_or_3_probability)
print("\tимеет сумму цифр 9:", sum_of_digits_9_probability)
print("\tимеет сумму цифр, делящуюся на 3:", sum_of_digits_divisible_by_3_probability)


Задача 1: Вероятность что цифры на красном и синем кубиках совпали: 0.165665
Задача 2: Наиболее вероятная сумма цифр на кубиках: 7
Задача 3: Вероятность, что выбранное число:
	чётно: 0.500054
	делится на 3: 0.300337
	делится и на 2, и на 3: 0.150119
	не делится ни на 2, ни на 3: 0.349728
	имеет сумму цифр 9: 0.099966
	имеет сумму цифр, делящуюся на 3: 0.300337
